CREATE TABLE Category
(
    CategoryID UNIQUEIDENTIFIER NOT NULL, 
    ClientID UNIQUEIDENTIFIER NOT NULL, 
	CategoryName NVARCHAR(250) NULL,
    CreatedBy UNIQUEIDENTIFIER NULL,
    CreatedOn DATETIME NULL,
    ModifiedBy UNIQUEIDENTIFIER NULL,
    ModifiedOn DATETIME NULL,
    [IsDeleted] BIT NULL DEFAULT 0, 
    CONSTRAINT [PK_Category] PRIMARY KEY ([CategoryID])
);

