CREATE TABLE [dbo].[Client]
(
	ClientID UNIQUEIDENTIFIER PRIMARY KEY,
    [Name] NVARCHAR(250) NOT NULL,
    Email NVARCHAR(250) NOT NULL,
    ContactNo NVARCHAR(250) NOT NULL,
    [Address] NVARCHAR(MAX)  NULL,
    ApiKey NVARCHAR(250) NULL,
	CreatedBy UNIQUEIDENTIFIER NULL,
    CreatedOn DATETIME NULL,
    ModifiedBy UNIQUEIDENTIFIER NULL,
    ModifiedOn DATETIME NULL,
    [IsDeleted] BIT NULL DEFAULT 0, 
)
