CREATE TABLE Item
(
    ItemID INT IDENTITY(1,1) NOT NULL, 
	ClientID UNIQUEIDENTIFIER NOT NULL, 
    [Name] NVARCHAR(250) NULL,
    [Description] NVARCHAR(MAX) NULL,
    [Price] DECIMAL(10, 2) NULL,
    ImgURL NVARCHAR(512) NULL,
    [Stock] INT NULL,
    CategoryID INT NULL,
    BrandID INT NULL,
    CreatedBy UNIQUEIDENTIFIER NULL,
    CreatedOn DATETIME NULL,
    ModifiedBy UNIQUEIDENTIFIER NULL,
    ModifiedOn DATETIME NULL,
    [IsDeleted] BIT NULL DEFAULT 0, 
    CONSTRAINT [PK_Item] PRIMARY KEY ([ItemID])
);

